# Site settings
title: "VishwaCTF 25 Mini Writeups"
description: CTF Writeups @deathwing
baseurl: "/vishwactf25mini-writeups"
url: ""

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Just the Docs specific settings
search_enabled: true
heading_anchors: true

# Color scheme
color_scheme: light

# Navigation
aux_links:
  "View on GitHub":
    - "//github.com/iamabhi747/vishwactf25mini-writeups"

# Sidebar navigation
nav:
  - title: "VishwaCTF 25 Mini"
    url: /
    children:
      - title: "Cryptography"
        url: /cryptography/
        children:
          - title: "18th Century"
            url: /cryptography/18thcentury/
          - title: "Timestuck"
            url: /cryptography/timestuck/
      - title: "Digital Forensics"
        url: /forensics/
        children:
          - title: "Dateslip Logs"
            url: /forensics/datesliplogs/
          - title: "Encrypted Canvas"
            url: /forensics/encryptedcanvas/
      - title: "Miscellaneous"
        url: /miscellaneous/
        children:
          - title: "Architect Enigma"
            url: /miscellaneous/architectenigma/
          - title: "Compression"
            url: /miscellaneous/compression/
          - title: "Welcome"
            url: /miscellaneous/welcome/
          - title: "Whispering Wings"
            url: /miscellaneous/whisperingwings/
      - title: "Reverse Engineering"
        url: /re/
        children:
          - title: "Crack Me"
            url: /re/crackme/
          - title: "FIGHT FIGHT FIGHT"
            url: /re/fightfightfight/
          - title: "Faulpelz"
            url: /re/faulpelz/
      - title: "Steganography"
        url: /steganography/
        children:
          - title: "Lost Evidence"
            url: /steganography/lostevidence/
      - title: "Web Exploitation"
        url: /web/
        children:
          - title: "pay your own loan"
            url: /web/payyourownloan/

# Footer content
footer_content: "Copyright &copy; 2024. Distributed under the MIT license."

# Enable syntax highlighting
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor